const Test = require('./unittest.js')


const test = new Test();

test.assertEqual(2, 2, 'should be equal')
test.assertEqual('hi', 'hi', 'yo yo')
test.assertEqual(-1, -1, 'lol')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')
test.assertEqual(1, -1, 'yolo')

test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.assertEqual(-1, -1, 'yolo')
test.main();
