name: Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test unittest
    steps:
      - uses: actions/checkout@v2
      - name: set up node 
        uses: actions/setup-node@v2
        with:
          node-version: 15
        - run: npm version
        - run: ./tests.sh

